---

- hosts: "pm1"
  become: yes
  become_user: root
  vars_files:
    - '../inventory/group_vars/distro/{{ ansible_distribution|lower }}{{ ansible_distribution_major_version }}.yml'

  tasks:

  - name: "Creating Shared Folder"
    file:
      path: /var/lib/columnstore/{{ item }}
      state: directory
    loop:
        - data1
        - data2
        - data3
        - storagemanager

  - name: "Deleting EFS Volume"
    efs:
      state: absent
      name: '{{ item }}'
      access_key: '{{ aws_access_key_id }}'
      secret_key: '{{ aws_secret_access_key }}'
      region: '{{ aws_region }}'
    loop:
        - data1
        - data2
        - data3
        - storagemanager

  - name: "Creating StorageManager EFS Volumes"
    efs:
      state: present
      name: '{{ item }}'
      access_key: '{{ aws_access_key_id }}'
      secret_key: '{{ aws_secret_access_key }}'
      region: '{{ aws_region }}'
      encrypt: yes
      tags:
        Name: '{{ item }}'
        purpose: high-availability
      targets:
        - subnet_id: '{{ aws_subnet }}'
          security_groups: [ '{{ aws_security_group }}' ]
    loop:
        - data1
        - data2
        - data3
        - storagemanager

- hosts: "pm"
  become: yes
  become_user: root
  vars_files:
    - '../inventory/group_vars/distro/{{ ansible_distribution|lower }}{{ ansible_distribution_major_version }}.yml'

  tasks:

  - name: "Getting EFS Info"
    efs_info:
      access_key: '{{ aws_access_key_id }}'
      secret_key: '{{ aws_secret_access_key }}'
      region: '{{ aws_region }}'
    register: efs_info
    delegate_to: 'pm1'
    run_once: true

  - name: "Setting EFS System Facts"
    set_fact:
      efs_volume0: "{{ efs_info.efs[0].name + ':' + efs_info.efs[0].file_system_id }}"
      efs_volume1: "{{ efs_info.efs[1].name + ':' + efs_info.efs[1].file_system_id }}"
      efs_volume2: "{{ efs_info.efs[2].name + ':' + efs_info.efs[2].file_system_id }}"
      efs_volume3: "{{ efs_info.efs[3].name + ':' + efs_info.efs[3].file_system_id }}"
    delegate_to: 'pm1'
    run_once: true

  - name: "Waiting For EFS To Be Available"
    shell: sleep 20

  - name: "Mounting EFS Volumes"
    mount:
      name: '/var/lib/columnstore/{{ item.name }}'
      src: '{{ aws_zone }}.{{ item.file_system_id }}.efs.{{ aws_region }}.amazonaws.com:/'
      fstype: nfs4
      opts: nfsvers=4.1
      state: mounted
    loop:
      - { name: "{{ efs_volume0.split(':')[0] }}", file_system_id: "{{ efs_volume0.split(':')[1] }}" }
      - { name: "{{ efs_volume1.split(':')[0] }}", file_system_id: "{{ efs_volume1.split(':')[1] }}" }
      - { name: "{{ efs_volume2.split(':')[0] }}", file_system_id: "{{ efs_volume2.split(':')[1] }}" }
      - { name: "{{ efs_volume3.split(':')[0] }}", file_system_id: "{{ efs_volume3.split(':')[1] }}" }
