---

- hosts: "pm,mx"
  become: yes
  become_user: root
  vars_files:
    - '../inventory/group_vars/distro/{{ ansible_distribution|lower }}{{ ansible_distribution_major_version }}.yml'

  tasks:

  - name: "Checking Running Services"
    service_facts:

  - name: "Setting SELinux Permissive"
    selinux:
      policy: targeted
      state: permissive

  - name: "Disabling firewalld"
    systemd:
      name: firewalld
      state: stopped
      enabled: no
    when: (ansible_facts.services["firewalld.service"]["state"]) is defined

  - name: "Upgrading All Packages"
    package:
      name: '*'
      state: latest
      update_cache: yes
    when: run_upgrade == 'true'

  - name: "Rebooting To Apply Updates"
    reboot:
    when: run_upgrade == 'true'

  - name: "Installing Some Prerequisites"
    package:
      name: '{{ item }}'
      state: present
    with_items:
      - '{{ boto }}'
      - '{{ gcc }}'
      - '{{ git }}'
      - '{{ htop }}'
      - '{{ jemalloc }}'
      - '{{ jq }}'
      - '{{ mlocate }}'
      - '{{ nano }}'
      - '{{ python_dev }}'
      - '{{ python3_requests }}'
      - '{{ tar }}'
      - '{{ unzip }}'
      - '{{ wget }}'

  - name: "Setting System Character Set"
    command: localedef -i en_US -f UTF-8 en_US.UTF-8

  - name: "Adjusting System vm.swappiness"
    sysctl:
      name: vm.swappiness
      value: '10'
      state: present

  - name: "Adjusting System vm.vfs_cache_pressure"
    sysctl:
      name: vm.vfs_cache_pressure
      value: '10'
      state: present

  - name: "Adjusting System net.core.rmem_max"
    sysctl:
      name: net.core.rmem_max
      value: '16777216'
      state: present

  - name: "Adjusting System net.core.wmem_max"
    sysctl:
      name: net.core.wmem_max
      value: '16777216'
      state: present

  - name: "Adjusting System net.ipv4.tcp_rmem"
    sysctl:
      name: net.ipv4.tcp_rmem
      value: '4096 87380 16777216'
      state: present

  - name: "Adjusting System net.ipv4.tcp_wmem"
    sysctl:
      name: net.ipv4.tcp_wmem
      value: '4096 65536 16777216'
      state: present

  - name: "Adjusting System net.ipv4.tcp_no_metrics_save"
    sysctl:
      name: net.ipv4.tcp_no_metrics_save
      value: '1'
      state: present

  - name: "Adjusting System net.core.netdev_max_backlog"
    sysctl:
      name: net.core.netdev_max_backlog
      value: '2500'
      state: present

  - name: "Adding Custom Mappings To /etc/hosts"
    blockinfile:
      path: /etc/hosts
      block: |
        {{ hostvars['pm1_private'].ansible_host }} pm1
        {{ hostvars['pm2_private'].ansible_host }} pm2
        {{ hostvars['pm3_private'].ansible_host }} pm3
        {{ hostvars['mx1_private'].ansible_host }} mx1

  - name: "Removing Conflicts"
    package:
      name: '{{ mariadb_libs }}'
      state: absent

- hosts: "pm1"
  become: yes
  become_user: root

  tasks:

  - name: "Removing Old S3 Bucket"
    s3_bucket:
      name: '{{ s3_bucket }}'
      access_key: '{{ s3_access_key_id }}'
      secret_key: '{{ s3_secret_access_key }}'
      region: '{{ s3_region }}'
      state: absent
      force: yes
    when: use_s3 == true

  - name: "Creating New S3 Bucket"
    s3_bucket:
      name: '{{ s3_bucket }}'
      access_key: '{{ s3_access_key_id }}'
      secret_key: '{{ s3_secret_access_key }}'
      region: '{{ s3_region }}'
      state: present
    when: use_s3 == true
